background {
  color = rgba(1a1a1aee)
}

label {
  text = $TIME
  color = rgba(33ccffee)
  font_size = 64
  halign = center
  valign = center
}

input-field {
  size = 300, 50
  outer_color = rgba(33ccffee)
  inner_color = rgba(1a1a1acc)
  font_color = rgba(ffffffee)
  halign = center
  valign = center
  position = 0, -100
}
