---
name: Build disk images

on:
  workflow_dispatch:
    inputs:
      upload-to-s3:
        description: 'Upload to S3'
        required: false
        default: false
        type: boolean
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64
  pull_request:
    branches:
      - main
    paths:
      - './disk_config/disk.toml'
      - './disk_config/iso.toml'
      - './.github/workflows/build-disk.yml'

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_REGISTRY: 'ghcr.io/${{ github.repository_owner }}'
  DEFAULT_TAG: 'latest'
  BIB_IMAGE: 'quay.io/centos-bootc/bootc-image-builder:latest

jobs:
  build:
    name: Build disk images
    runs-on: >-
      ${{
        (inputs.platform || 'amd64') == 'amd64'
        && 'ubuntu-24.04'
        || 'ubuntu-24.04-arm'
      }}

    strategy:
      fail-fast: false
      matrix:
        disk-type: ['qcow2', 'anaconda-iso']

    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          USER_UID=$(id -u)
          USER_GID=$(id -g)
          DISK_TYPE=$(echo '${{ matrix.disk-type }}' | tr ' ' '-')

          echo 'IMAGE_REGISTRY=${IMAGE_REGISTRY,,}' >> '$GITHUB_ENV'
          echo 'IMAGE_NAME=${IMAGE_NAME,,}' >> '$GITHUB_ENV'
          echo 'DISK_TYPE=${DISK_TYPE}' >> '$GITHUB_ENV'
          echo 'USER_UID=${USER_UID}' >> '$GITHUB_ENV'
          echo 'USER_GID=${USER_GID}' >> '$GITHUB_ENV'

      - name: Install container dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build disk images
        id: build
        uses: osbuild/bootc-image-builder-action@8661cd3832544ad68c12dcde8681b13ab0f56a8d # main
        with:
          builder-image: ${{ env.BIB_IMAGE }}
          config-file: ${{ matrix.disk-type == 'anaconda-iso' && './disk_config/iso.toml' || './disk_config/disk.toml' }}
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          chown: ${{ env.USER_UID }}:${{ env.USER_GID }}
          types: ${{ matrix.disk-type }}
          additional-args: --use-librepo=True --rootfs ext4
